### ISSUE TITLE
How can I make it better?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/touch-bar-simulator#1]
I already added a screenshot button to make it easy to capture a screenshot of the Touch Bar.

What else can I do to make it better? Any other useful things I could add?

**Comment by c-cho** [comment]
Maybe shortcuts to show/hide the touch bar?

**Comment by w3code** [comment]
Nice work!

It would be great to have the ability to pin it on any of the screen-borders (not only top or bottom, but right or left, too).

**Comment by sindresorhus** [comment]
You mean vertically? I don't think that's possible. Open to suggestions though.

**Comment by w3code** [comment]
Yes, I meant vertically. Just an idea :-)

**Comment by sfhosley** [comment]
How about ditching the title bar at the top of the window? I know that's how one drags the window around (and it's where the close and screenshot buttons are), but getting rid of it would make it feel a lot more like a native tool, rather than a simulator.

**Comment by sindresorhus** [comment]
@sfhosley Probably not going to happen. That makes it hard to move it around and we use the toolbar for even more things now (#7).

**Comment by sfhosley** [comment]
Fair enough. Maybe the option to _hide_ it then? 😀

**Comment by tete1030** [comment]
Display the touch bar simulator on iPhone like what Duet Display is doing. But Duet Display makes iphone as an external monitor, it only display a rather small touch bar at bottom of the iPhone screen. I think showing a line-wrapped touch bar that full-fill the iphone screen would be a good idea.

**Comment by LoganDark** [comment]
Maybe support 10.12.1 😢 
![](https://cloud.githubusercontent.com/assets/4723091/25789700/818fb8da-3367-11e7-8676-a12b100deb2a.png)

**Comment by sindresorhus** [comment]
@LoganDark Not going to happen.

**Comment by sindresorhus** [comment]
Closing as I've gotten the feedback I need. Thanks all :)
