### ISSUE TITLE
Find a better way to launch the simulator

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/touch-bar-simulator#11]
See: https://github.com/sindresorhus/touch-bar-simulator/pull/9#issuecomment-289658188

**This about finding a finding a better way to hook into the actual touch bar instance and launch it. Not a user facing change.**

**Comment by Petapton** [comment]
See [here](https://github.com/sindresorhus/touch-bar-simulator/pull/13)

**Comment by sindresorhus** [comment]
@Petapton This is not about launching this app, but rather find a better way to interact with the actual simulator.

**Comment by ylluminate** [comment]
Is there a way to make it appear and disappear near the cursor when activating? That would help a lot since you have to use the mouse / trackpad to interact with the bar...

**Comment by sindresorhus** [comment]
@ylluminate That's unrelated to this issue and not something I'm interested in adding.

**Comment by ylluminate** [comment]
Oh really? I entirely misinterpreted your intention then since I had tied this into launching.

**Comment by sindresorhus** [comment]
I edited the issue description to be clearer.
