### ISSUE TITLE
Unable to toggle off immediately after toggling on

### ISSUE THREAD

**Issue by joshnh** [sindresorhus/touch-bar-simulator#15]
Toggling the touch bar on is fine, but you need to click into an app before you're able to toggle it off again.

**Comment by NightMachinary** [comment]
Indeed, it seems to be a focus-stealing problem. Doing command-q doesn't close the app that had focus before toggle either.

**Comment by sindresorhus** [comment]
In version 3, the app now lives in the menu bar and you can toggle it from the menu bar icon. https://github.com/sindresorhus/touch-bar-simulator/releases/tag/v3.0.0
