### ISSUE TITLE
Questions about hiding vs quitting

### ISSUE THREAD

**Issue by ylluminate** [sindresorhus/touch-bar-simulator#16]
Since `Touch Bar Simulator` does not have a Dock icon and is not readily hide-able, are there some key identifiers that could be used to trigger hiding via AppleScript?

Normally I could trigger a `hide` command vs just quit if I could understand how to access the `hide` command...  My goal is to hide/show with a keypress.  I currently have that working via Keyboard Maestro, however I am having to start/quit the app each time I want to show and hide it respectively.  The startup and quit take a little more time than I'd like and so it would be better if it could be left running and just be able to be hidden vs quit.

**Comment by sindresorhus** [comment]
`Touch Bar Simulator` launches in less than a second for me.

You might be able to use AppleScript and System Events, but I'm not sure.

Something like this maybe:

```applescript
tell application "System Events" to tell process "Touch Bar Simulator" to activate
```

*(Doesn't work though)*

**Comment by ylluminate** [comment]
Yeah, I've not been able to get "Touch Bar Simulator" to do anything. Sadly it takes a little longer for me (~3 seconds).

**Comment by sindresorhus** [comment]
In version 3, the app now lives in the menu bar and you can toggle it from the menu bar icon. https://github.com/sindresorhus/touch-bar-simulator/releases/tag/v3.0.0
