### ISSUE TITLE
Support scaling the Touch Bar

### ISSUE THREAD

**Issue by cheft** [sindresorhus/touch-bar-simulator#18]

**Comment by sindresorhus** [comment]
I don't think that's possible as it's emulating the real Touch Bar, which has a set width.

**Comment by Zarkstar** [comment]
Would it be possible to make it scalable at least? I'm using it in a 4k touch display and the small dimension of the button is a bit frustrating.

**Comment by sindresorhus** [comment]
That might be possible. Could maybe apply a scale transform to the view. Not something I personally need, but I welcome a pull request.

**Comment by sindresorhus** [comment]
Actually, I don't think this is something I want as it would not be a good experience. The UI would have to be pixel upscaled, which would make it blurry.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
