### ISSUE TITLE
Don't include the frameworks in the repo

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/touch-bar-simulator#2]
I need to find a way to copy the frameworks from Xcode when building instead of having them manually embedded here. Help wanted.

**Comment by yycking** [comment]
Sorry for my bad English.
When you add frameworks, unclick "Destination: Copy items if needed"
It will auto copy framework to your app without clone to your project.

**Comment by yycking** [comment]
Just need modify  project.pbxproj
In PBXFileReference section, change the value to
path = /Applications/Xcode.app/Contents/Frameworks/xxx.framework; sourceTree = "<absolute>";
