### ISSUE TITLE
Possibly a Safari favourites icon bug?

### ISSUE THREAD

**Issue by leggsimon** [sindresorhus/touch-bar-simulator#22]
So I've been trying to add a nicer icon for Safari users in their favourites for FT.com like the Guardian's, BBC's, and the others on the right

<img width="1085" alt="screenshot 2017-12-26 20 39 44" src="https://user-images.githubusercontent.com/11544418/34364350-0067baf0-ea7d-11e7-9e47-fcf2f00252a2.png">

So I added the necessary code to a local version of the page and loaded it up on a computer with a touch bar and it loads ok.

![ft-apple-touch-bar-icon](https://user-images.githubusercontent.com/11544418/34364418-cfd17fe2-ea7d-11e7-993d-7af84696fcae.jpg)

I wanted a better screenshot to add to a PR so I downloaded this to screenshot the change and it seems to render the bookmark's text as well.

<img width="1085" alt="screenshot 2017-12-26 20 41 08" src="https://user-images.githubusercontent.com/11544418/34364402-9399c886-ea7d-11e7-85c1-bc29cc83afdf.png">

*Edit:* It seems to be subdomains it doesn't like, since the test bacbook I was using was loading my local using `ip.address:PORT` and I was bookmarking using `local.ft.com:PORT`. I've noticed all the subdomain bookmarks have the text as well. I don't have access to the computer now so I can't check if that is the case on the real touch bar so am not sure if it is a bug with this or not.

**Comment by sindresorhus** [comment]
Closing as this is most likely a bug with the actual Touch Bar too. We only present the built-in Touch Bar here, nothing else.
