### ISSUE TITLE
Toggle doesn't work when the touchbar is open in another space

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/touch-bar-simulator#24]
Toggle doesn't work when the touchbar is open in another space. No matter how many times I toggle, it doesn't open in the current app's space.

**Comment by OJ7** [comment]
Drag the "Touch Bar Simulator App" to your dock. Right click on the app --> Options --> Assign To All Desktops.

**Comment by sindresorhus** [comment]
In version 3, the app now lives in the menu bar and you can toggle it from the menu bar icon. https://github.com/sindresorhus/touch-bar-simulator/releases/tag/v3.0.0
