### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by mayowadavid** [sindresorhus/touch-bar-simulator#26]
Hello @sindresorhus I found your project to be lovely then i intend to make a logo that meet up your project

### This are what inspire the logo creation, a hand, rectangular bar and alphabet s.
![tools-touch-bar-status-process](https://user-images.githubusercontent.com/34623610/40574851-1a75fd00-60d2-11e8-8487-61629be2f6ed.png)
***
![touch-bar-status-400](https://user-images.githubusercontent.com/34623610/40574874-54760f36-60d2-11e8-8330-0582cd55d739.png)
#### If you like them i will make other size variation and also provide the editable files.

**Comment by mayowadavid** [comment]
@sindresorhus

**Comment by sindresorhus** [comment]
@mayowadavid I appreciate the effort, but this project already has a logo ;)

If you're looking for to help out with logos, check out projects that need it: https://github.com/search?q=logo+needed&state=open&type=Issues
