### ISSUE TITLE
Fails at launch

### ISSUE THREAD

**Issue by heyAyushh** [sindresorhus/touch-bar-simulator#28]
```
“Touch Bar Simulator” can’t be opened because the identity of the developer cannot be confirmed.
```
macOS mojave public beta 5

Chrome downloaded this file today at 7:31 AM from sindresorhus.com.

**Comment by sindresorhus** [comment]
Try right-clicking the app, select "Open", and then accept the warning about unidentified app. You should only have to do this the first time.

**Comment by heyAyushh** [comment]
Not working but this time i didn't get the above warning

**Comment by LoganDark** [comment]
@sindresorhus The app crashes on launch. I think the APIs changed.

**Comment by sindresorhus** [comment]
Yes, I've confirmed this too. Not much I can do about it until we solve #27.

**Comment by sindresorhus** [comment]
I have made it work in Mojave now.

Can you confirm it's working?
https://dsc.cloud/sindresorhus/Touch-Bar-Simulator.app-1536944459
(The binary is large, see #29)

**Comment by LoganDark** [comment]
No, because that server's upload speed is under 1 MB**it** per second.

I'm not waiting 3 hours to download this on unstable WiFi.

**Comment by sajjaadf** [comment]
I get A error message, here it is 
Sep 18 18:29:14 Sajjaads-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000024.Touch Bar Simulator[11214]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[10664]
Sep 18 18:30:08 Sajjaads-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000028.Touch Bar Simulator[11273]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[10664]
Sep 18 18:30:48 Sajjaads-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000002a.Touch Bar Simulator[11308]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[11303]
Process:               Touch Bar Simulator [10894]
Path:                  /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
Responsible:           Touch Bar Simulator [10894]
  Referenced from: /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
 in /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109528000 -        0x10952dff7 +com.sindresorhus.Touch-Bar-Simulator (1.2.0 - 1.2.0) <5AF606DC-4168-3DA3-ACC6-52B9E6D4D0C6> /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
       0x10953c000 -        0x10955aff7  com.apple.dt.instruments.DVTInstrumentsUtilities (8.3.2 - 62080) <5D8134A3-2F02-33C0-8AC9-EDC84A328789> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsUtilities.framework/Versions/A/DVTInstrumentsUtilities
       0x109581000 -        0x109588ffb  com.apple.kperfdataDT (1.0 - 1) <23AB879A-2D17-3757-9E0D-BE4353BED036> /Applications/Touch Bar Simulator.app/Contents/Frameworks/kperfdataDT.framework/Versions/A/kperfdataDT
       0x109591000 -        0x109601fdf  com.apple.SymbolicationDT (8.3.2 - 62052) <73A434D3-0F11-35B1-AA6F-FDC8AC3A86F7> /Applications/Touch Bar Simulator.app/Contents/Frameworks/SymbolicationDT.framework/Versions/A/SymbolicationDT
       0x109658000 -        0x1096e3fff  com.apple.CoreSymbolicationDT (8.3.2 - 62048) <3A507F73-854B-387B-BBAC-5D0D2B002CB1> /Applications/Touch Bar Simulator.app/Contents/Frameworks/CoreSymbolicationDT.framework/Versions/A/CoreSymbolicationDT
       0x109737000 -        0x1097e6fff  com.apple.dt.instruments.DVTInstrumentsFoundation (8.3.2 - 62080) <A3364AED-3483-36DE-A316-83F09B27486B> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
       0x10988a000 -        0x1098b5fff  com.apple.dt.instruments.DTXConnectionServices (8.3.2 - 62080) <D53251C8-6058-3ADD-8D76-EAAF4B2CE688> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices
       0x1098dd000 -        0x1098dfff3  com.apple.dt.DVTDeviceFoundation (8.3.2 - 1) <2FF1941F-29D1-34E1-9CA1-5ADA5F2147FC> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTDeviceFoundation.framework/Versions/A/DVTDeviceFoundation
       0x1098e8000 -        0x109990ff3  com.apple.dt.XCTest (1.0 - 12124) <F4D9CF74-6243-303A-9343-B818D3356C52> /Applications/Touch Bar Simulator.app/Contents/Frameworks/XCTest.framework/Versions/A/XCTest
       0x109a21000 -        0x109d5cfff  com.apple.dt.DVTKit (8.3.2 - 12153) <C07DC5E2-EC09-3965-B9AA-01F233BAE0CB> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109f83000 -        0x109fc5ff7 +org.sparkle-project.Sparkle (1.17.0 - 1.17.0) <ADBA750E-9348-39F6-B51D-3F43D3ACC941> /Applications/Touch Bar Simulator.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10a00b000 -        0x10a01cfff  com.apple.dt.IDE.DFRSupportKit (8.2.1 - 7104) <07844223-B119-35E1-AB94-68F17809F924> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DFRSupportKit.framework/Versions/A/DFRSupportKit
       0x10a037000 -        0x10a59eff7  com.apple.dt.DVTFoundation (8.3.2 - 12153) <0307E7EC-DE01-35E7-98F3-9993F6568288> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTFoundation.framework/Versions/A/DVTFoundation
       0x10a7f9000 -        0x10a805fff +libswiftAppKit.dylib (3.1 - 802.0.53) <F3EE8627-3CB7-3ECE-B79D-9CA8298466A9> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftAppKit.dylib
       0x10a819000 -        0x10aa9bff7 +libswiftCore.dylib (3.1 - 802.0.53) <F3C2AEFF-073B-3D90-9F72-0CAA3B814A23> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCore.dylib
       0x10ad6d000 -        0x10ad77fff +libswiftCoreData.dylib (3.1 - 802.0.53) <1A670783-4A8C-37E3-A907-50A677DB7D5E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreData.dylib
       0x10ad8c000 -        0x10ad9afff +libswiftCoreGraphics.dylib (3.1 - 802.0.53) <739DD9C7-DB67-3B64-A139-48CACD44741A> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreGraphics.dylib
       0x10adba000 -        0x10adbeffe +libswiftCoreImage.dylib (3.1 - 802.0.53) <07D26DC6-DC2F-3966-BC87-0EA6FC215C07> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreImage.dylib
       0x10adc9000 -        0x10adcffff +libswiftDarwin.dylib (3.1 - 802.0.53) <A5DE2CCA-D683-31C5-A6B4-1DC5831D0EF3> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDarwin.dylib
       0x10ade2000 -        0x10adfdff7 +libswiftDispatch.dylib (3.1 - 802.0.53) <CB9C8886-19E3-352A-B8C4-02C7ECD18738> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDispatch.dylib
       0x10ae39000 -        0x10af24ff7 +libswiftFoundation.dylib (3.1 - 802.0.53) <7FED0AEF-4FBE-3EDA-AAB3-41262EC6B33E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftFoundation.dylib
       0x10b031000 -        0x10b034ff3 +libswiftIOKit.dylib (3.1 - 802.0.53) <9408AC1E-676A-32B8-8E1A-4F2A4D5675BD> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftIOKit.dylib
       0x10b03c000 -        0x10b041fff +libswiftObjectiveC.dylib (3.1 - 802.0.53) <C5FD2292-A97E-33FD-B1F8-02C9250021BA> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftObjectiveC.dylib
       0x10b052000 -        0x10b058ff7 +libswiftQuartzCore.dylib (3.1 - 802.0.53) <D9A41D53-AA11-30B5-8247-9B5BFAACD7F0> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftQuartzCore.dylib
       0x10b065000 -        0x10b068ff3 +libswiftXPC.dylib (3.1 - 802.0.53) <5ED57C16-AB3A-3B11-A714-C246CCCCFE82> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftXPC.dylib

**Comment by LoganDark** [comment]
...

**Comment by sajjaadf** [comment]
Process:               Touch Bar Simulator [10894]
Path:                  /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
Responsible:           Touch Bar Simulator [10894]
  Referenced from: /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
 in /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109528000 -        0x10952dff7 +com.sindresorhus.Touch-Bar-Simulator (1.2.0 - 1.2.0) <5AF606DC-4168-3DA3-ACC6-52B9E6D4D0C6> /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
       0x10953c000 -        0x10955aff7  com.apple.dt.instruments.DVTInstrumentsUtilities (8.3.2 - 62080) <5D8134A3-2F02-33C0-8AC9-EDC84A328789> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsUtilities.framework/Versions/A/DVTInstrumentsUtilities
       0x109581000 -        0x109588ffb  com.apple.kperfdataDT (1.0 - 1) <23AB879A-2D17-3757-9E0D-BE4353BED036> /Applications/Touch Bar Simulator.app/Contents/Frameworks/kperfdataDT.framework/Versions/A/kperfdataDT
       0x109591000 -        0x109601fdf  com.apple.SymbolicationDT (8.3.2 - 62052) <73A434D3-0F11-35B1-AA6F-FDC8AC3A86F7> /Applications/Touch Bar Simulator.app/Contents/Frameworks/SymbolicationDT.framework/Versions/A/SymbolicationDT
       0x109658000 -        0x1096e3fff  com.apple.CoreSymbolicationDT (8.3.2 - 62048) <3A507F73-854B-387B-BBAC-5D0D2B002CB1> /Applications/Touch Bar Simulator.app/Contents/Frameworks/CoreSymbolicationDT.framework/Versions/A/CoreSymbolicationDT
       0x109737000 -        0x1097e6fff  com.apple.dt.instruments.DVTInstrumentsFoundation (8.3.2 - 62080) <A3364AED-3483-36DE-A316-83F09B27486B> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
       0x10988a000 -        0x1098b5fff  com.apple.dt.instruments.DTXConnectionServices (8.3.2 - 62080) <D53251C8-6058-3ADD-8D76-EAAF4B2CE688> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices
       0x1098dd000 -        0x1098dfff3  com.apple.dt.DVTDeviceFoundation (8.3.2 - 1) <2FF1941F-29D1-34E1-9CA1-5ADA5F2147FC> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTDeviceFoundation.framework/Versions/A/DVTDeviceFoundation
       0x1098e8000 -        0x109990ff3  com.apple.dt.XCTest (1.0 - 12124) <F4D9CF74-6243-303A-9343-B818D3356C52> /Applications/Touch Bar Simulator.app/Contents/Frameworks/XCTest.framework/Versions/A/XCTest
       0x109a21000 -        0x109d5cfff  com.apple.dt.DVTKit (8.3.2 - 12153) <C07DC5E2-EC09-3965-B9AA-01F233BAE0CB> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109f83000 -        0x109fc5ff7 +org.sparkle-project.Sparkle (1.17.0 - 1.17.0) <ADBA750E-9348-39F6-B51D-3F43D3ACC941> /Applications/Touch Bar Simulator.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10a00b000 -        0x10a01cfff  com.apple.dt.IDE.DFRSupportKit (8.2.1 - 7104) <07844223-B119-35E1-AB94-68F17809F924> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DFRSupportKit.framework/Versions/A/DFRSupportKit
       0x10a037000 -        0x10a59eff7  com.apple.dt.DVTFoundation (8.3.2 - 12153) <0307E7EC-DE01-35E7-98F3-9993F6568288> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTFoundation.framework/Versions/A/DVTFoundation
       0x10a7f9000 -        0x10a805fff +libswiftAppKit.dylib (3.1 - 802.0.53) <F3EE8627-3CB7-3ECE-B79D-9CA8298466A9> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftAppKit.dylib
       0x10a819000 -        0x10aa9bff7 +libswiftCore.dylib (3.1 - 802.0.53) <F3C2AEFF-073B-3D90-9F72-0CAA3B814A23> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCore.dylib
       0x10ad6d000 -        0x10ad77fff +libswiftCoreData.dylib (3.1 - 802.0.53) <1A670783-4A8C-37E3-A907-50A677DB7D5E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreData.dylib
       0x10ad8c000 -        0x10ad9afff +libswiftCoreGraphics.dylib (3.1 - 802.0.53) <739DD9C7-DB67-3B64-A139-48CACD44741A> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreGraphics.dylib
       0x10adba000 -        0x10adbeffe +libswiftCoreImage.dylib (3.1 - 802.0.53) <07D26DC6-DC2F-3966-BC87-0EA6FC215C07> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreImage.dylib
       0x10adc9000 -        0x10adcffff +libswiftDarwin.dylib (3.1 - 802.0.53) <A5DE2CCA-D683-31C5-A6B4-1DC5831D0EF3> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDarwin.dylib
       0x10ade2000 -        0x10adfdff7 +libswiftDispatch.dylib (3.1 - 802.0.53) <CB9C8886-19E3-352A-B8C4-02C7ECD18738> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDispatch.dylib
       0x10ae39000 -        0x10af24ff7 +libswiftFoundation.dylib (3.1 - 802.0.53) <7FED0AEF-4FBE-3EDA-AAB3-41262EC6B33E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftFoundation.dylib
       0x10b031000 -        0x10b034ff3 +libswiftIOKit.dylib (3.1 - 802.0.53) <9408AC1E-676A-32B8-8E1A-4F2A4D5675BD> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftIOKit.dylib
       0x10b03c000 -        0x10b041fff +libswiftObjectiveC.dylib (3.1 - 802.0.53) <C5FD2292-A97E-33FD-B1F8-02C9250021BA> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftObjectiveC.dylib
       0x10b052000 -        0x10b058ff7 +libswiftQuartzCore.dylib (3.1 - 802.0.53) <D9A41D53-AA11-30B5-8247-9B5BFAACD7F0> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftQuartzCore.dylib
       0x10b065000 -        0x10b068ff3 +libswiftXPC.dylib (3.1 - 802.0.53) <5ED57C16-AB3A-3B11-A714-C246CCCCFE82> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftXPC.dylib
``

**Comment by sajjaadf** [comment]
```
Process:               Touch Bar Simulator [10894]
Path:                  /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
Responsible:           Touch Bar Simulator [10894]
  Referenced from: /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
 in /Applications/Touch Bar Simulator.app/Contents/MacOS/../Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109528000 -        0x10952dff7 +com.sindresorhus.Touch-Bar-Simulator (1.2.0 - 1.2.0) <5AF606DC-4168-3DA3-ACC6-52B9E6D4D0C6> /Applications/Touch Bar Simulator.app/Contents/MacOS/Touch Bar Simulator
       0x10953c000 -        0x10955aff7  com.apple.dt.instruments.DVTInstrumentsUtilities (8.3.2 - 62080) <5D8134A3-2F02-33C0-8AC9-EDC84A328789> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsUtilities.framework/Versions/A/DVTInstrumentsUtilities
       0x109581000 -        0x109588ffb  com.apple.kperfdataDT (1.0 - 1) <23AB879A-2D17-3757-9E0D-BE4353BED036> /Applications/Touch Bar Simulator.app/Contents/Frameworks/kperfdataDT.framework/Versions/A/kperfdataDT
       0x109591000 -        0x109601fdf  com.apple.SymbolicationDT (8.3.2 - 62052) <73A434D3-0F11-35B1-AA6F-FDC8AC3A86F7> /Applications/Touch Bar Simulator.app/Contents/Frameworks/SymbolicationDT.framework/Versions/A/SymbolicationDT
       0x109658000 -        0x1096e3fff  com.apple.CoreSymbolicationDT (8.3.2 - 62048) <3A507F73-854B-387B-BBAC-5D0D2B002CB1> /Applications/Touch Bar Simulator.app/Contents/Frameworks/CoreSymbolicationDT.framework/Versions/A/CoreSymbolicationDT
       0x109737000 -        0x1097e6fff  com.apple.dt.instruments.DVTInstrumentsFoundation (8.3.2 - 62080) <A3364AED-3483-36DE-A316-83F09B27486B> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
       0x10988a000 -        0x1098b5fff  com.apple.dt.instruments.DTXConnectionServices (8.3.2 - 62080) <D53251C8-6058-3ADD-8D76-EAAF4B2CE688> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices
       0x1098dd000 -        0x1098dfff3  com.apple.dt.DVTDeviceFoundation (8.3.2 - 1) <2FF1941F-29D1-34E1-9CA1-5ADA5F2147FC> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTDeviceFoundation.framework/Versions/A/DVTDeviceFoundation
       0x1098e8000 -        0x109990ff3  com.apple.dt.XCTest (1.0 - 12124) <F4D9CF74-6243-303A-9343-B818D3356C52> /Applications/Touch Bar Simulator.app/Contents/Frameworks/XCTest.framework/Versions/A/XCTest
       0x109a21000 -        0x109d5cfff  com.apple.dt.DVTKit (8.3.2 - 12153) <C07DC5E2-EC09-3965-B9AA-01F233BAE0CB> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTKit.framework/Versions/A/DVTKit
       0x109f83000 -        0x109fc5ff7 +org.sparkle-project.Sparkle (1.17.0 - 1.17.0) <ADBA750E-9348-39F6-B51D-3F43D3ACC941> /Applications/Touch Bar Simulator.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10a00b000 -        0x10a01cfff  com.apple.dt.IDE.DFRSupportKit (8.2.1 - 7104) <07844223-B119-35E1-AB94-68F17809F924> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DFRSupportKit.framework/Versions/A/DFRSupportKit
       0x10a037000 -        0x10a59eff7  com.apple.dt.DVTFoundation (8.3.2 - 12153) <0307E7EC-DE01-35E7-98F3-9993F6568288> /Applications/Touch Bar Simulator.app/Contents/Frameworks/DVTFoundation.framework/Versions/A/DVTFoundation
       0x10a7f9000 -        0x10a805fff +libswiftAppKit.dylib (3.1 - 802.0.53) <F3EE8627-3CB7-3ECE-B79D-9CA8298466A9> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftAppKit.dylib
       0x10a819000 -        0x10aa9bff7 +libswiftCore.dylib (3.1 - 802.0.53) <F3C2AEFF-073B-3D90-9F72-0CAA3B814A23> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCore.dylib
       0x10ad6d000 -        0x10ad77fff +libswiftCoreData.dylib (3.1 - 802.0.53) <1A670783-4A8C-37E3-A907-50A677DB7D5E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreData.dylib
       0x10ad8c000 -        0x10ad9afff +libswiftCoreGraphics.dylib (3.1 - 802.0.53) <739DD9C7-DB67-3B64-A139-48CACD44741A> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreGraphics.dylib
       0x10adba000 -        0x10adbeffe +libswiftCoreImage.dylib (3.1 - 802.0.53) <07D26DC6-DC2F-3966-BC87-0EA6FC215C07> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftCoreImage.dylib
       0x10adc9000 -        0x10adcffff +libswiftDarwin.dylib (3.1 - 802.0.53) <A5DE2CCA-D683-31C5-A6B4-1DC5831D0EF3> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDarwin.dylib
       0x10ade2000 -        0x10adfdff7 +libswiftDispatch.dylib (3.1 - 802.0.53) <CB9C8886-19E3-352A-B8C4-02C7ECD18738> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftDispatch.dylib
       0x10ae39000 -        0x10af24ff7 +libswiftFoundation.dylib (3.1 - 802.0.53) <7FED0AEF-4FBE-3EDA-AAB3-41262EC6B33E> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftFoundation.dylib
       0x10b031000 -        0x10b034ff3 +libswiftIOKit.dylib (3.1 - 802.0.53) <9408AC1E-676A-32B8-8E1A-4F2A4D5675BD> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftIOKit.dylib
       0x10b03c000 -        0x10b041fff +libswiftObjectiveC.dylib (3.1 - 802.0.53) <C5FD2292-A97E-33FD-B1F8-02C9250021BA> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftObjectiveC.dylib
       0x10b052000 -        0x10b058ff7 +libswiftQuartzCore.dylib (3.1 - 802.0.53) <D9A41D53-AA11-30B5-8247-9B5BFAACD7F0> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftQuartzCore.dylib
       0x10b065000 -        0x10b068ff3 +libswiftXPC.dylib (3.1 - 802.0.53) <5ED57C16-AB3A-3B11-A714-C246CCCCFE82> /Applications/Touch Bar Simulator.app/Contents/Frameworks/libswiftXPC.dylib

```

**Comment by sajjaadf** [comment]
That Binary is Soo big!

**Comment by sindresorhus** [comment]
I found a better way to solve this that will result in a much smaller binary. I'll have it out soon.

**Comment by sindresorhus** [comment]
Just in time for Mojave, here's a rewritten version: https://dsc.cloud/sindresorhus/Touch-Bar-Simulator-2.0.0-1537818011 (Only 7 MB) Please let me know whether it works fine or not. If it works, I'll do a release tomorrow.

**Comment by LoganDark** [comment]
It works! Thank you <3

**Comment by sindresorhus** [comment]
@LoganDark Can you also try the screenshot (camera) button on the top-right of the window?

**Comment by LoganDark** [comment]
Yeah, I did. Makes no sound but drops an image on the desktop.

**Comment by LoganDark** [comment]
@sajjaadf Excuse me, but what's your problem?

**Comment by sindresorhus** [comment]
@sajjaadf One comment is enough.
