### ISSUE TITLE
Make it a menu bar app

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/touch-bar-simulator#30]
So people can toggle it by pressing the menu bar icon. We could then also support #21 and support setting a hotkey.

This would fix #16 and maybe #15.

**Comment by GoldenChaos** [comment]
Oh man, can't wait for this! I'm the developer of [GoldenChaos-BTT](https://community.folivora.ai/t/goldenchaos-btt-a-complete-touch-bar-ui-replacement-preset/1281), a popular BetterTouchTool preset.

TouchBarDemoApp seems to have finally given up the ghost and crashes too constantly now to use, so this has become my main Touch Bar app now! TouchBarDemoApp was incredible and had a lot of VERY useful features, especially not having a title bar and a client app for iPad (with a fully-functioning keyboard! that I even used as my full-time keyboard for a while!).

I've found the way TouchBarDemoApp works to be the best among all the existing Touch Bar simulator apps, so I really just wanted to add my +1 to this ticket and say I'm for this particular update.

I'm not sure I know enough to submit a PR for this, but if you need any design help I'm at your service :)

**Comment by GoldenChaos** [comment]
Any updates on this feature? Right now I'm stuck using Touche, which is not a very pretty app and feels like it's going to break any moment now.

If there's any way I can be helpful, please let me know since I use these apps for testing GC-BTT.

**Comment by sajjaadf** [comment]
https://github.com/matryer/bitbar
