### ISSUE TITLE
Touchbar disappears

### ISSUE THREAD

**Issue by tomads** [sindresorhus/touch-bar-simulator#36]
If the Touchbar is configured using the Finder, the Touchbar is not displayed. Buttons can therefore not be added or removed. 
This does not happen with other Touchbar simulators.

**Comment by sindresorhus** [comment]
> If the Touchbar is configured using the Finder

What does this mean?

**Comment by tomads** [comment]
You can configure the Touchbar by using Finder Menu 'View/Customize Touchbar'.
When using this, the Touchbar disappears. There is only a gray screen with the customize view ...
