### ISSUE TITLE
Toggle Shortcut not working

### ISSUE THREAD

**Issue by JxD-DeciSion** [sindresorhus/touch-bar-simulator#40]
I think I tried every possible combination of preferences and shortcuts, but somehow I can't manage to get the toggling shortcut working. Toggling via the menubar icons works properly.

**Comment by Jamesxxx1997** [comment]
I have same question

**Comment by ThatsJustCheesy** [comment]
I unfortunately can't reproduce this. Make sure the frontmost application has a "Services" menu in its application menu in the menu bar. e.g., Safari is frontmost > menu bar > Safari > Services. In that menu, ensure "Toggle Touch Bar" has a shortcut listed next to it.

If it does, then a) launch Touch Bar Simulator, and then b) click the Toggle Touch Bar menu item. Does the touch bar toggle then? If not, it's something to do with the service handler.

**Comment by ThatsJustCheesy** [comment]
Yes. From the front page:

> You can add a toggle shortcut in System Preferences → Keyboard → Shortcuts → Services → Toggle Touch Bar.

Navigate to the Keyboard system preferences, then click the Shortcuts tab and then click Services on the left. Scroll the list down to the "General" section, and check the box beside "Toggle Touch Bar" and add your shortcut on the right.

Let us know if it still doesn't work.

**Comment by Jamesxxx1997** [comment]
I can confirm that shortcut is working.
However , When I toggle on the Touch Bar via shortcut , I have to switch to another application or virtual desktop , otherwise the shortcut stop functioning ; This problem doesn't exist when I click the menubar icon to toggle the touchbar.

**Comment by ThatsJustCheesy** [comment]
Yes, this is an unforunate limitation of the way we currently accomplish the shortcut. If it's sufficiently annoying, then we could change the mechanism, but that would likely require an additional dependency (MASShortcut or similar) and some UI to manage the shortcut. If you'd really like to see this, please open a new issue for it.

Hope you're enjoying the app otherwise!
