### ISSUE TITLE
Google Chrome Audio/Video Skip Bar Glitch

### ISSUE THREAD

**Issue by FrostBird347** [sindresorhus/touch-bar-simulator#41]
When playing a video/audio file it either does not show it at all or it does not allow you to change the video time
![glitch](https://user-images.githubusercontent.com/39435218/57531240-8fa28b00-736b-11e9-843b-872418de7f60.png)
Testing it on Youtube and Soundcloud caused the bar to appear, but it is impossible to change the video time.
Testing it on a downloaded video on chrome (or embedded youtube video on discord) does not show the bar at all.

Testing it on itunes works though.

I will test more apps when I can

### Here is the list of apps I have tested so far:

**Works:**
```
itunes
Quicktime player
Safari on youtube, soundcloud and downloaded video
```

**Shows bar but is like the image:**
```
Google chrome on youtube and soundcloud
```

**Does not show anything at all:**
```
Discord
Google Chrome on downloaded video
```

**Comment by sindresorhus** [comment]
What is shown in the Touch Bar is not in our control. This is most definitely a bug in Chrome. This app just presents the Touch Bar simulator view that is built into macOS.

You should report it to Chrome: https://bugs.chromium.org/p/chromium/issues/list?can=2&q=%22touch+bar%22

**Comment by FrostBird347** [comment]
Thanks!
