### ISSUE TITLE
(Request) Resizable Window

### ISSUE THREAD

**Issue by d1One** [sindresorhus/touch-bar-simulator#45]
Any chance of making the Bar resizable? Would be cool so I could use it on an external touchscreen.

**Comment by sindresorhus** [comment]
Duplicate of #18

**Comment by sindresorhus** [comment]
It's possible, but it would be blurry if enlarged...

**Comment by MikeGolden** [comment]
Actually I've got the same request. If it's possible, I'd appreciate it.

**Comment by sindresorhus** [comment]
@MikeGolden What do you need it for? Do you need to enlarge or reduce the size?

**Comment by htkoca** [comment]
Probably to make the touch bar span the width of te display if I had to guess

**Comment by d1One** [comment]
In my case, it was to reduce it's size so it fits my small external touch screen.

**Comment by Radek-Suski** [comment]
I was actually thinking the same. I have a spare  7" touchscreen display. I could basically use it to have kinda Touch Bar ;)

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
