### ISSUE TITLE
How do you know DFRSupportKit.framework

### ISSUE THREAD

**Issue by onmyway133** [sindresorhus/touch-bar-simulator#5]
Hi, this is just brilliant and convenient to use Touch Bar. Just a question, how do you know that `IDETouchBarSimulatorHostWindowController` is inside `DFRSupportKit`, and how do you figure out what frameworks it depends on? Like why do we need `XCTest`?

**Comment by sindresorhus** [comment]
[`RuntimeBrowser`](https://github.com/nst/RuntimeBrowser) is a very handy app to browse framework headers. You can find private frameworks in `/System/Library/PrivateFrameworks`. Most of the frameworks used here are in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks`. When I included `DFRSupportKit` and tried to compile, it complained that it was missing a referenced framework, so I included the mentioned framework, tried to compile, it failed, included the next framework mentioned, and kept doing that until it compiled. No idea why `XCTest` is needed. I guess some code in those frameworks depend on it.

**Comment by yycking** [comment]
When you running app without depend frameworks.
You will got issue like "image not found"

dyld: Library not loaded: @rpath/DTXConnectionServices.framework/Versions/A/DTXConnectionServices
  Referenced from:....../Contents/Frameworks/DVTFoundation.framework/Versions/A/DVTFoundation
  Reason: image not found
