### ISSUE TITLE
brew install fail

### ISSUE THREAD

**Issue by L1cardo** [sindresorhus/touch-bar-simulator#51]
Can not be installed with home brew.
I know this is a homebrew issue , but this has to be the owner to fix.

![截屏2019-07-07下午9 59 27](https://user-images.githubusercontent.com/33802186/60769458-81ba7d80-a102-11e9-8524-a77666e121be.png)

**Comment by sindresorhus** [comment]
Open an issue on Homebrew. I don't control how that works.

Relevant: https://github.com/Homebrew/homebrew-cask/commit/c96d5a1bc7376d7fd346b44a93f9d4af4277f4fe
