### ISSUE TITLE
Thanks for the great little app! Happen to know how to access the private mission control API for a CTRL+MIDDLE CLICK to close an expose window? 

### ISSUE THREAD

**Issue by 01GOD** [sindresorhus/touch-bar-simulator#52]
Thanks for the great little app! Happen to know how to access the private mission control API for a CTRL+MIDDLE CLICK to close an expose window? 

Saw the mention of knowing how to access a private OS API. 

Thanks in advance!

**Comment by ThatsJustCheesy** [comment]
Not sure I follow… was it something like [this](https://apple.stackexchange.com/questions/302812/close-window-with-middle-mouse-button-in-expose) you were looking for?

If you're up to such a challenge, you could look into, for example, writing a SIMBL plugin that injects code into a system process (WindowServer?) that would monitor exposé windows and middle-mouse events, etc. It wouldn't exactly be easy. (If you're still up to it, google class-dump, and befriend it along with your debugger)

In the end, this really has nothing to do with this app.

Best of luck though!

**Comment by 01GOD** [comment]
Thanks for the info! (BTT isn't freeware, although it used to be, so I
thought it would be a nice quick project to make an alternative for that)
