### ISSUE TITLE
Specify constant distance from edge

### ISSUE THREAD

**Issue by GoldenChaos** [sindresorhus/touch-bar-simulator#55]
When docked to the bottom of the screen, Touch Bar Simulator covers up dock icon labels. When I used the floating window option before docking was a thing, I would always float the window 20px or so above the dock to make room for the dock labels.

Would be great to be able to define this, possibly with a lil slider in the menu bar above "transparency".

If this feature is added, my recommendation is to have all four corners be rounded if the Touch Bar simulator window is not directly against the edge.

**Comment by sindresorhus** [comment]
What labels? Can you include a screenshot?

**Comment by GoldenChaos** [comment]
Here's an example, you can see the name "Amazon" is cut off:

![Screen Shot 2019-11-15 at 4 33 01 PM](https://user-images.githubusercontent.com/1396727/68977171-9ea84100-07c5-11ea-91cf-6e8193e211e9.png)

I would much prefer to have the Touch Bar float a short distance above the dock or bottom of the screen. The only way to accomplish that right now is to have it floating, which adds back the title bar UI I don't want, and makes it draggable, which I also don't want.

For people with different tastes, a slider that adjusts the distance the Touch Bar floats from the dock/menu bar/edge of the screen could be added to the menu bar item's menu underneath the "transparency" setting.

**Comment by ThatsJustCheesy** [comment]
I'll handle this one.

The rounded corners thing is already being discussed in another issue and PR. Once that's merged we can combine the two ideas and have all four corners rounded when distance from screen edge ≠ 0.
