### ISSUE TITLE
Does not work on macOS Catalina

### ISSUE THREAD

**Issue by isidorn** [sindresorhus/touch-bar-simulator#61]
MacOS Catalina
Instal latestl TouchBar Simluartor version 
Clicking on any of the actions does not work. No matter what app I use underaneath, any click on the touch bar has no effect. For example clicking on `esc` does not close the simulator.

I believe this was working with the previous TouchBar Simulator. Though I upgraded from one version of Catalina to the latest so that might have also caused the issue.

Thanks!

**Comment by sindresorhus** [comment]
Have you tried [this](https://github.com/sindresorhus/touch-bar-simulator#clicking-in-the-simulator-window-is-not-working)?

**Comment by isidorn** [comment]
Yeah. Does not help. Since it is checked, and I can not uncheck it for some weird reason.

**Comment by abrown435** [comment]
I have the same issue. The app installs on MacOS Catalina, but is not responsive. Toggling settings in system preferences doesn't seem to help.

**Comment by y4rr** [comment]
Confirm this issue. Setting any of these permissions doesn't help:
kTCCServiceScreenCapture
kTCCServiceListenEvent
kTCCServiceAccessibility

I've debugged the code a little and everything looks fine on the surface, it calls DFRFoundationPostEventWithMouseActivity, but then nothing happens on their side.

**Comment by y4rr** [comment]
@sindresorhus AHAH it seems that I have figured out how to make the app responsive to the mouse, but only temporarily:
1. Open Xcode.
2. Open its own touch bar simulator from Window -> Touch Bar.
3. Close it.
4. Open TouchBarSimulator, or any other app that does the same thing (for example https://github.com/bikkelbroeders/TouchBarDemoApp).
Now, the touch bar will respond to the mouse, BUT only until you close this instance of the app.

**Comment by sindresorhus** [comment]
I looked into this today and I've discovered that it happens when you either:
1. Open Xcode.
2. Open a different Touch Bar simulator app.
3. Relaunch Touch Bar Simulator.

So my conclusion is that somehow we're corrupting some state when starting the simulator, which makes it not work the second time.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
