### ISSUE TITLE
Hide Touch Bar Simulator when a contextual menu is being displayed behind it

### ISSUE THREAD

**Issue by GoldenChaos** [sindresorhus/touch-bar-simulator#62]
This is espeically annoying when positioned above the dock, and it blocks the ability to quit apps:

![Screen Shot 2019-11-15 at 7 14 57 PM](https://user-images.githubusercontent.com/1396727/68984108-70822b80-07dc-11ea-8d32-b289636b589d.png)

I’m not sure if there’s a way to have Touch Bar Simulator detect when these menus are being shown behind it and quickly fade itself out, but that would be the optimal UX in my opinion.

I _don’t_ think it should hide for app name bubbles, though. Just for right click context menus.

**Comment by sindresorhus** [comment]
I don't know about any way to detect context menus, but PR welcome if anyone knows how to solve this.

**Comment by ThatsJustCheesy** [comment]
I think I've got a working way to detect this, using the Accessibility UIElement APIs that we already require access to. Just have to iron out bugs and add add some UI, will put up a PR soon.

**Comment by ThatsJustCheesy** [comment]
Update: I've got it working 100% for menus from the active application, which is better than nothing but also not complete. I'm not sure how assistive apps are supposed to detect Dock menus, as observing the `com.apple.dock` application doesn't work (though there _has_ to be a way). Status bar menus may well be the trickiest to detect; I've briefly tried keeping track of open apps with `LSUIElement` enabled, and I think it could work, but it might require more custom code to retrieve the relevant `Info.plist`s as `Bundle` wasn't of much help for some reason.

The main reason I'm working on this feature is that it's a really bad experience to have Touch Bar Simulator covering its own options menu when it's docked-to-top.

My current work is [here](https://github.com/ThatsJustCheesy/touch-bar-simulator/tree/hide-for-menus).

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
