### ISSUE TITLE
Not Working on MacBook Pro 16-inch Model 

### ISSUE THREAD

**Issue by L1cardo** [sindresorhus/touch-bar-simulator#64]
Touch-Bar-Simulator kills Touch Bar on `MacBook Pro 16-inch` model.
Touch Bar goes to black when I start Touch-Bar-Simulator.
![IMG_0096](https://user-images.githubusercontent.com/33802186/69252910-b54bff00-0bee-11ea-8779-8edb92d81c6c.png)

hardware: MacBook Pro (16-inch, 2019)
software: 10.15.1 (19B2106)

**Comment by L1cardo** [comment]
Any idea?

**Comment by ThatsJustCheesy** [comment]
Looking at recent Xcode release notes…

<img width="544" alt="Screen Shot 2019-12-14 at 4 42 58 PM" src="https://user-images.githubusercontent.com/16456186/70854972-454d3380-1e91-11ea-9f37-8987ab9f2821.png">

it looks like there's a different API for this new touch bar model.

**Comment by L1cardo** [comment]
I compiled a build with the latest version of Xcode, it still did not work.
I don’t know if this problem is caused by codes or api.

**Comment by ThatsJustCheesy** [comment]
Yeah, someone's going to have to dig into the new Xcode binaries and find the new APIs. I could do it sometime in the next couple days if no one else wants to do it sooner.

@sindresorhus

**Comment by ThatsJustCheesy** [comment]
Actually, come to think of it: does anyone know what happens when this app is run on a non-16 in MacBook that has a Touch Bar? Does it mirror it on the main screen, kill it on both…?

I could try it on a family member's machine sometime.

**Comment by L1cardo** [comment]
touch bar simulator can display Pock, but can not display the original Touch Bar

**Comment by L1cardo** [comment]
@real-cereal-boy This is true. But I like to close my macbook pro and  connect a extra display while I am using it.  I can also do some debugging on touch-bar-simulator

**Comment by sindresorhus** [comment]
Relevant discussion: https://github.com/asmagill/hammerspoon_asm.undocumented/issues/10

**Comment by sindresorhus** [comment]
I have a build with a possible fix. Could anyone try it out?

[Touch Bar Simulator.app.zip](https://github.com/sindresorhus/touch-bar-simulator/files/4180434/Touch.Bar.Simulator.app.zip)

**Comment by L1cardo** [comment]
@sindresorhus  I have tested on my 16 inch macbook pro, it works fine ！
![image](https://user-images.githubusercontent.com/33802186/74146250-a8fa9f80-4c3b-11ea-8394-33fb3c9153ff.png)
![image](https://user-images.githubusercontent.com/33802186/74146262-b0ba4400-4c3b-11ea-9398-f80fa0642a16.png)
