### ISSUE TITLE
Touchbar below the dock

### ISSUE THREAD

**Issue by sidpremkumar** [sindresorhus/touch-bar-simulator#69]
Would it be possible to implement the feature to have the touch bar below the dock? And then extend across the screen? I see #45 to extend the size, but nothing about below the dock.

**Comment by sindresorhus** [comment]
“Below the Dock” as in depth or position?

**Comment by sidpremkumar** [comment]
As in position, across the bottom of the screen

**Comment by sindresorhus** [comment]
If I understand you correctly, there's no way to move the Dock up to place the Touch Bar window below it.

**Comment by sidpremkumar** [comment]
Ah okay got it thanks
