### ISSUE TITLE
Touch Bar is offline when I use External display. With closing MacBook Pro 

### ISSUE THREAD

**Issue by Nikolassos** [sindresorhus/touch-bar-simulator#70]
Touch Bar is offline when I use External display. With closing MacBook Pro

**Comment by LinnStanton** [comment]
I am also seeing this. Interestingly, it is not immediate. When I close the laptop the touchbar continues to operate for a time (which varies)and then goes black. I am running 10.15.5

**Comment by baaskaas** [comment]
i'm having the same strugles on an mbp 15.6" 2018. I have a wall mount for the laptop and an usb-c monitor. Touch Bar Simulator runs fine with the display open, but thats when i don't need it. When the display closes Touch Bar Simulator immediately turns to a black window. like it is displaying the touchbar on a window. If i touch the touchbar i see it on the window on my display.

**Comment by Lotuashvili** [comment]
@sindresorhus Any update about this? The whole point of using this software for me was using it on closed Macbook with external display.

**Comment by sindresorhus** [comment]
I don't have an external display, so I'm not able to even reproduce this.

**Comment by kitt1987** [comment]
This issue exists in Monterey even without an external monitor. The simulator prints some related logs while debugging.

```
2021-12-16 15:03:03.738093+0800 Touch Bar Simulator[240:18286708] [General] Accessibility: Not vending elements because elementWindow(1000) is lower than shield(2147483628)
```

**Comment by petugg** [comment]
I actually thought the whole point with TBS was to have a Touchbar also when in clamshell mode. If you need to have the lid open, you only end up with two Touchbars. Of course, not on the new MBPs that have no TB, but clamshell mode would still be a very useful feature.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
