### ISSUE TITLE
Transparency slider is not fully visible on Big Sur

### ISSUE THREAD

**Issue by haykam821** [sindresorhus/touch-bar-simulator#75]
On Big Sur, the transparency slider is lower than it should be, giving the appearance that it is cut off.

![Misaligned transparency slider](https://user-images.githubusercontent.com/24855774/93280058-bf9b4300-f796-11ea-8e8e-449bde02337b.png)

**Comment by Doregon** [comment]
I've just upgraded to Big Sur on my MBA and the transparency slider is where is should be for me. Is there a set of steps you can follow to invoke the problem so I can try seeing if it happens to me?

**Comment by haykam821** [comment]
The transparency slider is in the right place now, but now the close button is offset:

![image](https://user-images.githubusercontent.com/24855774/97647846-a2aa8e80-1a29-11eb-9a0f-47d688d853e9.png)

**Comment by Doregon** [comment]
I wonder if it moves with the slider's position on the x-axis... because I just realized my close button is the tiniest bit offset too.

**Comment by Doregon** [comment]
I think that it's the new UI. The more cozy system interface messes with a lot of apps and pulls them away from each other. I'm guessing we just need an Xcode 12 version of this sim

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
