### ISSUE TITLE
Hide the touchbar when the dock is visible + hide ESC 

### ISSUE THREAD

**Issue by antoniomcr96** [sindresorhus/touch-bar-simulator#77]
This app is awesome. Thanks for all your work.
I would suggest a (probably) simple enhancement, if possible. 

Hide the bar only on the main screen (when dock is visible on the bottom of the screen):
![image](https://user-images.githubusercontent.com/63928525/100099033-25730d80-2e5f-11eb-87c1-52510a2ddcfb.png)

And only show it in full screen desktops (when dock is hidden). 
![image](https://user-images.githubusercontent.com/63928525/100099111-43407280-2e5f-11eb-9eeb-7329cea3ed08.png)
Without the padding from the bottom that is caused (probably) by the fixed distance from the dock.

This would require to automatically hide Touch Bar if dock appears:
![image](https://user-images.githubusercontent.com/63928525/100099445-bea22400-2e5f-11eb-8ec5-00f6642741e2.png)

EDIT: I would propose also an option to hide the "ESC" key. 

I hope this would be possible and require a short time. You did an amazing job. Thanks

**Comment by martin-braun** [comment]
Yes, this is a bummer at the moment. Automatically hiding the dock and showing it when touching the bottom edge will cause these problems: 

<img width="850" alt="Screen Shot 2023-04-17 at 11 05 48 PM" src="https://user-images.githubusercontent.com/24259245/232611409-91fda2d3-42ca-41ef-bb93-a1fe484f2cd2.png">

But why hiding the touch bar? It should be enough to let the touch bar automatically move up when the dock reveals in the same way it does when the dock is permanently shown.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
