### ISSUE TITLE
Lockscreen

### ISSUE THREAD

**Issue by rcarlosibal** [sindresorhus/touch-bar-simulator#83]
When the screen turns off after a few minutes away or when your lockscreen appears the virtual touchbar stop working, you have to reset the app, for me its pretty useful because my real touchbar lcd doesnt works, but the bar actually does, so the virtual one gives me a visual guide to use the real one, but its annoying when i have to reset the app lot of times per day

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
