### ISSUE TITLE
Issues about new MacBook Pro without touch bar

### ISSUE THREAD

**Issue by lijiexi** [sindresorhus/touch-bar-simulator#85]
Hi, I love this app. It works nicely in my old mbp(with touch bar).
I would like to know if this software works properly on newer mbp(without touch bar).
I want to use this app and BTT to simulate touch bar when I use new MBP.
Best Wish

**Comment by ThatsJustCheesy** [comment]
It still works on my M1 Macbook Air (2020, no touch bar), running macOS 12.4.

**Comment by lijiexi** [comment]
Thanks a lot. That's a great help.
