### ISSUE TITLE
M2 MacBookPro empty Touch Bar no buttons appear

### ISSUE THREAD

**Issue by irudkin** [sindresorhus/touch-bar-simulator#87]
Thank you for this app (from **rudkini**).
Using the Touch Bar from the 4.2.0 package  from this repository on a M2 MacBookPro Ventura 13.0.
I believe I have given the program all its required permissions to open and run.
The app pops up a window which does not contain any Touch Bar buttons. The opaque slider works. The drop menu from the menu bar does not work.
It works on an Intel MacPro Ventura 13.1 though the bar does not still in the same place when app focus changes on a multi-screen setup.
Use the bar for Final Cut Pro X 

@sindresorhus

**Comment by sindresorhus** [comment]
This is a known issue. Something with the Touch Bar changed and I haven't been able to track down how to fix it.

Try https://redsweater.com/touche/ Maybe it works better.

**Comment by AndDevDE** [comment]
I think I've found a - at least temporary - solution to the problem:
Right click the menu bar icon, turn "Hide and Show Automatically" on, then off.
This fixed it for me.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
