### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by martin-braun** [sindresorhus/touch-bar-simulator#88]
Some apps do not support the touch bar and thus you get a black bar. It would be nice if there was an option to use the black-part of the touch bar as mask to turn it transparent, so that you only see the buttons and not the dark background. 

Additionally, it should then be possible to click-through black sections, so that if the app doesn't support the touch bar, we can interact with UI elements that hide behind the transparent bar.

Would this be possible?

**Comment by acelticsfan** [comment]
I invert the colors on my Mac using accessibility features in MacOS.  It would be helpful if we could make only the buttons visible and the rest of the bar completely transparent (i.e. not visible).  

As it stands, when the colors are inverted on the display, the black background becomes white even if you set the transparency to 0.5.

**Comment by acelticsfan** [comment]
![image](https://github.com/sindresorhus/touch-bar-simulator/assets/76820710/3a9a63e7-c7c8-4a41-a33e-61cc45eea189)

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
