### ISSUE TITLE
Bug: Docked touch bar moves to primary screen when brightness changes while being on fullscreen on external monitor

### ISSUE THREAD

**Issue by martin-braun** [sindresorhus/touch-bar-simulator#89]
I use the touch bar simulator on an external touch screen. I docked it to the bottom after moving it to the external screen, so it is displayed on the extern screen. 

As long as I am on a desktop space, I can change the brightness of the primary screen without problems. However, when I attempt to change the brightness of my primary in-build screen, the dock will jump to the main screen, if I am on a full-screen space on the external screen while doing it.

Please have a look to see how to reproduce: https://www.youtube.com/shorts/HsZsxp2gCl4

The hardware keys also cause this problem.

**Comment by martin-braun** [comment]
Update: It also happens sometimes when I bring an app on the main screen into focus, while not being in full-screen on any of the screens at all. This might be a different issue. If I know what it could be causing, I will provide more information in a new issue. It's hard to tell.

**Comment by martin-braun** [comment]
Update: It now also happens when I'm not in full-screen on my external monitor. Whenever I change brightness of my primary screen, the docked touch bar moves to my primary screen.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
