### ISSUE TITLE
not working touch bar

### ISSUE THREAD

**Issue by Yurka2012** [sindresorhus/touch-bar-simulator#92]
Mac 2019 macOS Monterey has only black Touch Bar what I *need* to do?

I download with the brew
<img width="1102" alt="Снимок экрана 2023-08-09 в 21 34 41" src="https://github.com/sindresorhus/touch-bar-simulator/assets/120343461/a201e8ac-40f0-4729-860d-803160273031">

**Comment by Yurka2012** [comment]
Waiting ....![image](https://github.com/sindresorhus/touch-bar-simulator/assets/120343461/850f9b74-5825-45fc-95ec-dfb6043a2580)

**Comment by Yurka2012** [comment]
day 2

**Comment by Yurka2012** [comment]
Day **3**

**Comment by etrahretep** [comment]
Try this:
https://github.com/jslegendre/TouchBar-Simulator
Build the latest one in Xcode

**Comment by Yurka2012** [comment]
Thanks!
