### ISSUE TITLE
Separate Part Of Display!

### ISSUE THREAD

**Issue by ViewbankCollege** [sindresorhus/touch-bar-simulator#93]
@sindresorhus I think it would be cool if you could have the touch bar simulator when dock on top you could make it would extend to so it would cover the whole display and it would sit on top of the menu bar. also this feature would be useful because you don't have to show and hide the touch bar every time you wanted to do anything that is placed underneath it. I know it may not be possible and may require you to jailbreak the mac

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
